*** Variables ***
${URL}                             https://shopist.io
${MY_PROFILE_BUTTON_SELECTOR}      css=#__layout > div > div:nth-child(1) > div.navbar-large > div > div:nth-child(2) > a.profile > div > div
${EDIT_PROFILE_BUTTON_SELECTOR}    css=#main > section > a
${FIRST_NAME_SELECTOR}             css=#main > section > div > div:nth-child(3) > div:nth-child(1) > label
${SECOND_NAME_SELECTOR}            css=#main > section > div > div:nth-child(3) > div:nth-child(2) > label
${SAVE_PROFILE_BUTTON_SELECTOR}    css=#main > section > div > div.button-row > button.button.big.inverted
${OUTPUT_FILE}                    Results.csv